data:
    name: shapenet
    dataroot: /home/tristan/deeppointcloud-benchmarks/data
    shapenet:
        category: Airplane

training:
    shuffle: True
    num_workers: 2
    batch_size: 4
    cuda: 0

experiment:
    name: RSConv
    task: SEGMENTATION
    dataset: shapenet

models:
    SEGMENTATION:
        # This part describes a template model configuration
        TemplateModel:
            name: TemplateModel
            down_conv:
                module_name: TemplateModelDownConv
                ratios: []
                radius: []
                down_conv_nn: [[], [], ...]
            up_conv:
                module_name: TemplateModelUpConv
                ratios: []
                radius: []
                up_conv_nn: [[], [], ...]   
                up_k: []  
                skip: True
            innermost:
                module_name: InnerModule
                aggr: max
                nn: []
            mlp_cls: 
                nn: []
                dropout: 0.5

        RSConv:
            name: RSConv
            down_conv:
                module_name: RSConv
                ratios: [0.2, 0.25]
                radius: [0.1, 0.2]
                local_nn: [[10, 32, 16, 3], [10, 32, 64, 64]]
                down_conv_nn: [[3, 16, 32, 64], [64, 64, 128]]
            innermost:
                module_name: GlobalBaseModule
                aggr: max
                nn: [131, 128] #[3  + 128]
            up_conv:
                module_name: FPModule
                ratios: [1, 0.25, 0.2]
                radius: [0.2, 0.2, 0.1]
                up_conv_nn: [[256, 64], [128, 64], [64, 64]] #[128 + 128, ...], [64+64, ...]
                up_k: [1, 3, 3]
                skip: True
            mlp_cls:
                nn: [64, 64, 64, 64]
                dropout: 0.5

        # This part describes a KPConvModel model configuration
        KPConv:
            name: KPConv
            down_conv:
                module_name: KPConv
                ratios: [0.2, 0.25]
                radius: [0.1, 0.2]
                down_conv_nn: [[3, 32], [32, 64]]
            up_conv:
                module_name: SimpleUpsampleKPConv
                radius: [1, 0.2, 0.1]
                up_conv_nn: [[128, 128], [64, 64], [64, 64]]     
                mlp_nn: [[192, 64], [96, 64], [64, 64]]     
                up_k: [1, 3, 3]   
                skip: True    
            innermost:
                module_name: GlobalBaseModule
                aggr: max
                nn: [67, 128]
            mlp_cls: 
                nn: [64, 64, 64, 64]
                dropout: 0.5

        pointnet2:
            name: pointnet2
            down_conv:
                module_name: SAModule
                ratios: [0.2, 0.25]
                radius: [0.2, 0.4]
                down_conv_nn: [[3, 64, 64, 128], [131, 128, 128, 256]]
            up_conv:
                module_name: FPModule
                ratios: [1, 0.25, 0.2]
                radius: [1, 0.2, 0.1]
                up_conv_nn: [[1280, 256, 256], [384, 256, 128], [128, 128, 128, 128]]
                up_k: [1, 3, 3]   
                skip: True    
            innermost:
                module_name: GlobalBaseModule
                aggr: max
                nn: [259, 256, 512, 1024]
            mlp_cls: 
                nn: [128, 128, 128, 128]
                dropout: 0.5
