data:
    name: shapenet
    dataroot: /Volumes/Workspace/KP_Conv/data
    shapenet:
        category: Airplane

training:
    shuffle: True
    num_workers: 2
    batch_size: 2
    cuda: 0

tested_model:
    name: pointnet2
    task: SEGMENTATION

models:
    SEGMENTATION:
        KPConv:
            name: KPConv
            convs:
                input_nc: 3
                ratios: [0.2, 0.25]
                radius: [0.1, 0.2]
                down_conv_nn: [[3, 32], [32, 64]]
                up_conv_nn: [[192, 64], [96, 32]]
                up_k: [1, 3, 3]
            global:
                aggr: max
                nn: [64, 128]
            skip: True
        pointnet2:
            name: pointnet2
            convs:
                input_nc: 3
                ratios: [0.2, 0.25]
                radius: [0.1, 0.2]
                down_conv_nn: [[3, 16, 32], [35, 64, 64]]
                up_conv_nn: [[64, 32, 32], [160, 64, 64]]
                up_k: [1, 3, 3]
            global:
                aggr: max
                nn: [67, 128]
            skip: True
            mlp_cls: [32, 16]

             
                
            