[tool.poetry]
name = "kp_conv"
version = "0.1.0"
description = ""
authors = ["Nicolas <nicolas.chaulet@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
torch = "^1.3"
torch-scatter = "^1.4"
torch-sparse = "^0.4.3"
torch-cluster = "^1.4"
torch-geometric = "^1.3"
matplotlib = "^3.1"
hydra-core = "^0.11.2"

[tool.poetry.dev-dependencies]
pylint = "^2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
