# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
experiment:
    name: pointnet2
    task: segmentation
    dataset: s3dis

# parameters for Weights and Biases
wandb:
    project: benchmarking
    log: False

# Those arguments defines the training hyper-parameters
training:
    shuffle: True
    num_workers: 4
    batch_size: 8
    cuda: 1
    precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference 
    epochs: 350

# Those arguments defines the available datasets
data:
    shapenet: 
        name: shapenet
        dataroot: data
        category: Airplane

    # This dataset can be used only for classification
    modelnet: 
        name: modelnet
        dataroot: data
        number: 10

    # This dataset can be used only for classification
    s3dis: 
        name: s3dis
        dataroot: data
        fold: 5

defaults:
    - models: segmentation